name = "terminal"
license = "MIT"
licenselink = ""
description = "A simple, retro theme for Hugo."
homepage = "https://github.com/xqk"
tags = ["blog", "clean", "customizable", "dark", "highlighting", "minimal", "monotone", "multilingual", "personal", "responsive", "simple", "technical", "retro"]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.90

[author]
  name = "xqk"
  homepage = ""
  twitter = ""
