baseURL = '/'
languageCode = 'en-us'
title = '一起打怪升级呀'
theme = 'terminal'
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = "true"
paginate = 5

[author]
  name = "xqk"
  email = "xiaqiankun@outlook.com"
  link = "https://www.icl.site"

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = true

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # oneHeadingSize = true # default

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default


[languages]
  [languages.zh-cn]
    languageName = "简体中文"
    title = "一起打怪升级呀"
    subtitle = "别整太大鸭力,多鸡立自己qaq"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "显示更多"
    readMore = "阅读更多"
    readOtherPosts = "阅读其他文章"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "页面没找到..."
    missingBackButtonLabel = "返回主页"
    minuteReadingTime = "分钟阅读"
    words = "words"
    contentDir = 'content/zh-cn'

    [languages.zh-cn.params.logo]
      logoText = "ICL"
      logoHomeLink = "/"

    [languages.zh-cn.menu]
      [[languages.zh-cn.menu.main]]
        identifier = "about"
        name = "关于"
        url = "/zh-cn/about"
      [[languages.zh-cn.menu.main]]
        identifier = "showcase"
        name = "展示"
        url = "/zh-cn/showcase"

  [languages.en]
    languageName = "English"
    title = "Let's fight monsters and upgrade together"
    subtitle = "Don't put too much pressure on yourself, motivate yourself more. qaq"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"
    contentDir = 'content/en'

    [languages.en.params.logo]
      logoText = "ICL"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/en/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/en/showcase"

[markup]
  [markup.highlight]
    noClasses = false